---
abstract: 'verify Austrian Social Securtiy numbers'
author:
  - 'Mark Hofstetter <mark@hofstetter.at>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, Dist::Milla version v1.0.8, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-AT-SSN
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/MarkHofstetter/Business-AT-SSN/issues
  homepage: https://github.com/MarkHofstetter/Business-AT-SSN
  repository: https://github.com/MarkHofstetter/Business-AT-SSN.git
version: '0.9'
x_contributors:
  - 'Mark Hofstetter <mark@univie.ac.at>'
  - 'MarkHofstetter <mark@hofstetter.at>'
